server:
  port: 9090

#数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/role_management_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 13621498341kb
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis相关
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xde.entity
  config-location: classpath:config/mybatis-config.xml
